name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Dependencies
      run: |
        sudo apt-get --yes update
        sudo apt-get --yes install libsystemd-dev libcurl4-openssl-dev
    - name: Build Project
      run: make --jobs --always-make
